id: I9D4ABAEF
default_language: sa
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:29:34.676671
last_modified: 2023-02-10 00:29:34.676775
source_metadata:
  title: 'Nāgārjuna: Mūlamadhyamakakārikā'
  language: sa
bases:
  44E4:
    base_file: 44E4.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
